### ISSUE TITLE
www folder is empty

### ISSUE THREAD

**Issue by nemchik** [linuxserver/docker-tt-rss#32]
A user on discord reported having trouble and seeing an error in their logs so I did some additional testing and here's the results.

I spun up a brand new container with the following compose:
```yaml
  ttrss:
    container_name: ttrss
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    image: linuxserver/tt-rss
    ports:
    - ${TTRSS_PORT_80}:80
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DOCKERCONFDIR}/ttrss:/config
```
(some irrelevant parts removed like logging)

The first run had no issues. I stopped and started the container and the second run had the following error in the log:
```
[cont-init.d] 19-newdefault: executing...
mv: cannot stat '/defaults/default.incontainer': No such file or directory
[cont-init.d] 19-newdefault: exited 0.
```

I stopped and removed the container and recreated it (same config volume) and it did not have an error.

I stopped the container again and started it again (without recreating) and found the same error once again in the logs.

I checked the script in question that's causing the error and found this https://github.com/linuxserver/docker-tt-rss/blob/de8446230209af44a98f65f20eece2ef2adb027a/root/etc/cont-init.d/19-newdefault#L4-L5 which references `/config/www/tt-rss` which I do not have. I do have `/config/www` but no `tt-rss` inside it.
